/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agile;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Wei Keat
 */
public class UpdateStaff extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStaff
     */
    public UpdateStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jtfid = new javax.swing.JTextField();
        jbtretrieve = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        jtfname = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        jtfgender = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        jtfage = new javax.swing.JTextField();
        lblhp = new javax.swing.JLabel();
        jtfhp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfaddress = new javax.swing.JTextField();
        jtfaddress2 = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        jtfemail = new javax.swing.JTextField();
        lblposition = new javax.swing.JLabel();
        jtfposition = new javax.swing.JTextField();
        jbtupdate = new javax.swing.JButton();
        jbtcancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fastest Deliveryman");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Update Delivery Man");

        lblid.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblid.setText("Employ ID:");

        jbtretrieve.setBackground(new java.awt.Color(51, 255, 0));
        jbtretrieve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtretrieve.setText("Get Record");

        lblname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblname.setText("Name:");

        jtfname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblgender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblgender.setText("Gender:");

        jtfgender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblage.setText("Age:");

        lblhp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblhp.setText("H/P:");

        jtfhp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Address:");

        jtfaddress2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblemail.setText("Email:");

        jtfemail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblposition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblposition.setText("Position:");

        jtfposition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbtupdate.setBackground(new java.awt.Color(0, 204, 0));
        jbtupdate.setText("Update");
        jbtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtupdateActionPerformed(evt);
            }
        });

        jbtcancel.setBackground(new java.awt.Color(255, 0, 0));
        jbtcancel.setText("Cancel");
        jbtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblname)
                            .addComponent(lblid)
                            .addComponent(lblgender)
                            .addComponent(lblage)
                            .addComponent(lblhp)
                            .addComponent(jLabel2)
                            .addComponent(lblemail)
                            .addComponent(lblposition)
                            .addComponent(jbtupdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfaddress2)
                            .addComponent(jtfname)
                            .addComponent(jtfgender)
                            .addComponent(jtfage)
                            .addComponent(jtfid)
                            .addComponent(jtfhp)
                            .addComponent(jtfaddress)
                            .addComponent(jtfemail)
                            .addComponent(jtfposition, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtretrieve)
                            .addComponent(jbtcancel))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(jtfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtretrieve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(jtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgender)
                    .addComponent(jtfgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblage)
                    .addComponent(jtfage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhp)
                    .addComponent(jtfhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(jtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblposition)
                    .addComponent(jtfposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtupdate)
                    .addComponent(jbtcancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtupdateActionPerformed
        Component frame = null;
        JOptionPane.showMessageDialog(frame, "Delivery man record updated.");
    }//GEN-LAST:event_jbtupdateActionPerformed

    private void jbtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jbtcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtcancel;
    private javax.swing.JButton jbtretrieve;
    private javax.swing.JButton jbtupdate;
    private javax.swing.JTextField jtfaddress;
    private javax.swing.JTextField jtfaddress2;
    private javax.swing.JTextField jtfage;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfgender;
    private javax.swing.JTextField jtfhp;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtfname;
    private javax.swing.JTextField jtfposition;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblhp;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblposition;
    // End of variables declaration//GEN-END:variables
}
